name: Dominic Orchard
highlighter: rouge

# Defaults for blog posts
defaults:
  - scope:
      path: "_blog"
      type: "blog"
    values:
      layout: "blog-post"

collections:
  pubs:
    output: false
  talks:
    output: false
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/
